# Generated by Django 3.1 on 2021-03-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210326_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
