# Generated by Django 3.1 on 2021-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210326_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='default/default.jpg', upload_to='products/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='products/', verbose_name='Imagen adicional'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thirth_image',
            field=models.ImageField(blank=True, default='default/default.jpg', upload_to='products/', verbose_name='Imagen adicional'),
        ),
    ]
